mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    # which means we direct the http://127.0.0.1:8000/my_polls_app/
    # to my_polls_app/urls.py to get more information
    # => So, we need to add urls.py under my_polls_app/ folder
    url(r'^my_polls_app/', include('my_polls_app.urls',namespace="my_polls_app")),
    # 加 namespace 是為了不要搞混app, 且讓 url 'my_polls_app:xxxx' 可以用
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
'''
# old way
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''
# for change to generic views
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

# for detail of ListView and DetailView
# ref: https://docs.djangoproject.com/en/1.10/ref/class-based-views/generic-display/#django.views.generic.detail.DetailView

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    # get_queryset() is a default method from ListView,We over write it here.
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# vote keep in the same code. Because it is use to count ++ the vote
def vote(request, question_id):
    #return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>title</title>
    <!-- Bootstrap core CSS -->
    <link href="{%  static 'polls/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Ourown CSS, since we have bootstrap, we don't need it anymore -->
    <!-- <link href="{%  static 'polls/style.css' %}" rel="stylesheet" type="text/css"/>-->
  </head>

  <body>

    {% include "polls/header.html" %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">

        {% block main_content %}
        {% endblock %}
        {% include "polls/footer.html" %}
      </div>
    </div>



  </body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
    {% block main_content %}


      <h1>{{ question.question_text }}</h1>

      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
      <input type="submit" class="btn btn-success" value="Vote" />
      </form>

      <a href="{% url 'polls:index' %}"> <- Back to Question List </a>
    {% endblock %}

mysite/polls/templates/polls/footer.html
<footer>
  <p>&copy; 2016 Company, Inc.</p>
</footer>

mysite/polls/templates/polls/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="#">Project name</a>
     </div>
     <div id="navbar" class="navbar-collapse collapse">
       <form class="navbar-form navbar-right">
         <div class="form-group">
           <input type="text" placeholder="Email" class="form-control">
         </div>
         <div class="form-group">
           <input type="password" placeholder="Password" class="form-control">
         </div>
         <button type="submit" class="btn btn-success">Sign in</button>
       </form>
     </div><!--/.navbar-collapse -->
   </div>
 </nav>

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
    {% block main_content %}
      <h1>Choose a question</h1>

      {% if latest_question_list %}
          <ul>
          {% for question in latest_question_list %}

            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
          {% endfor %}
          </ul>
      {% else %}
          <p>No polls are available.</p>
      {% endif %}

    {% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
    {% block main_content %}


      <h1>{{ question.question_text }}</h1>

      <ul>
      {% for choice in question.choice_set.all %}
          <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
      {% endfor %}
      </ul>

      <a href="{% url 'polls:detail' question.id %}">Vote again?</a>

    {% endblock %}